### ISSUE TITLE
ユーザー登録後、ヘッダーにデフォルトのアイコンが表示されない

### ISSUE THREAD

**Issue by kouichi-c** [MasakiTeshigahara/Laravel_SNS3#1]
## 期待動作
ユーザー登録後になにかしらアイコンの画像が設定されていること

**Comment by MasakiTeshigahara** [comment]
新規ユーザは、男の子の画像が表示されるように設定しました。

**Comment by kouichi-c** [comment]
新規登録時にアイコン表示がされることを確認しました。
あと、動作確認のために てすと というアカウントを作成しましたので、
こちらはおてすきのときに削除しておいてください。
