### ISSUE TITLE
ヘッダーのユーザーアイコンが、自分以外のアイコンで表示される

### ISSUE THREAD

**Issue by kouichi-c** [MasakiTeshigahara/Laravel_SNS3#2]
## 再現手順

- 任意のユーザーでログインする
- ユーザー一覧をクリックする

## 問題点
ヘッダーのアイコンが自分以外のアイコンが表示されている

## 期待動作
あるユーザーでログインしたときは、常にログインしたときのユーザーアイコンが表示されること

## 類似事象
自分のプロフィール画面から、DM画面に遷移したときは、アイコンが表示されなくなる

**Comment by MasakiTeshigahara** [comment]
他のユーザーアイコンが表示される現象を改修し、自分のユーザーアイコンが表示されるよに設定いたしました。

**Comment by kouichi-c** [comment]
アイコン表示が改善されていることを確認しました。
