### ISSUE TITLE
[フォロー/フォロワー]が0人の場合、[フォロー/フォロワー]画面がメッセージのみとなる

### ISSUE THREAD

**Issue by kouichi-c** [MasakiTeshigahara/Laravel_SNS3#3]
## 再現手順

- 任意のユーザーでログインする
- ヘッダーのユーザーアイコン横のプルダウンメニューからフォローを選択する
- フォローしているユーザー全員のフォローを解除する
- "フォローしているアカウントはいません" の文字のみ表示される

## 問題点
ヘッダーすら表示されないためツイート一覧などに画面遷移できない

## 期待動作
ヘッダーを表示させ、HOME画面やツイート一覧画面に遷移できること

## 類似事象
フォロワーが0人の場合も同様に "フォローされているアカウントはいません" のみ表示され、他画面に遷移できない

**Comment by MasakiTeshigahara** [comment]
メッセージ変更しました。
フォロー数が0の時、「フォローしているユーザーはいません、フォローしてみよう！」とポップアップが表示され、ユーザー、一覧画面に遷移
フォローワー数が０の時「フォローされているユーザーはいません」とポップアップが表示され、ツイート一覧に遷移されるようにしました。

**Comment by kouichi-c** [comment]
フォローしているユーザーが0人のときに表示されるポップアップでOKボタンをクリック後、
ユーザー一覧に遷移後、次ページに遷移するとまたポップアップが表示されてしまう。
