### ISSUE TITLE
プロフィール編集画面でプロフィールテキストが空白となる

### ISSUE THREAD

**Issue by kouichi-c** [MasakiTeshigahara/Laravel_SNS3#4]
## 再現手順
任意のユーザーでログインする
ヘッダーのユーザーアイコン横のプルダウンメニューからプロフィールを選択する
プロフィール画面の歯車アイコンを選択し、プロフィール編集画面に遷移する

## 問題点
プロフィールテキストにスペースが表示され、設定していたプロフィールテキストが表示されない
さらにプロフィールテキストが空白では更新できないため不便

## 期待動作
プロフィール編集画面に遷移したときに、設定していたプロフィールテキストが表示されること

**Comment by MasakiTeshigahara** [comment]
プロフィールテキスト編集時、元々入力されているものを表示させるように改修いたしました。

**Comment by kouichi-c** [comment]
プロフィール編集画面で、設定済みプロフィールテキストが表示されていること、問題なく更新ができることを確認しました。
