### ISSUE TITLE
コメントができない

### ISSUE THREAD

**Issue by kouichi-c** [MasakiTeshigahara/Laravel_SNS3#5]
## 再現手順

- 任意のユーザーでログインする
- ツイート一覧画面に表示されているツイート(自分 or 他人)のコメントアイコンを選択する
- コメントを入力し、ツイートする ボタンを選択する
- 500 Server Error となりコメントができない

## 期待動作
コメント機能が正常に機能し、あるツイートに対してコメントができること

**Comment by MasakiTeshigahara** [comment]
コメントできるように改修いたしました。
確認お願いします。

**Comment by kouichi-c** [comment]
コメントできるようになったことを確認しました。
