### ISSUE TITLE
ヘッダーに"Laravel_SNS"の文字が2つあり、どちらも遷移先が違うためわかりづらい

### ISSUE THREAD

**Issue by kouichi-c** [MasakiTeshigahara/Laravel_SNS3#6]
## 問題点
ログイン後、ヘッダーを見ると、
左側にLaravel_SNSの文字があり、これを選択するとLaravelのトップ画面に遷移する
真ん中にもLaravel_SNSのロゴがあり、これを選択するとツイート一覧に遷移する

ロゴと文字という違いはあれど、パット見では区別がつかないためユーザーは混乱してしまう可能性がある

**Comment by MasakiTeshigahara** [comment]
左側のlaravel_SNSのボタンは、トップ画面に戻っても意味がないので削除しました。
中央はツイート一覧に遷移する、ロゴのボタンを配置しました。

**Comment by kouichi-c** [comment]
確認しました。似たようなボタンがなくなったためわかりづらさはなくなったかと思いますので、クローズします。
